<a href="https://colab.research.google.com/github/ArbabKhan-sudo/Nust_AI_Batch-1/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np
from numpy import array

## Arrays

A numpy array is a grid of values, all of the same type. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

## 1-dim arrays

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])  # Create a rank 1 array
print(a)

[1 2 3 4 5 6]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a[0]

1

# Slicing

[1 2 3 4 5 6]


In [ ]:
a[2 : 5]

array([3, 4, 5])

In [ ]:
# To get the rank/axis of the array numpy provide ndim
a.ndim

1

In [ ]:
# Return number of values axis wise
# RC
a.shape
# R/C

(6,)

In [ ]:
# Return the type of elements
a.dtype

In [ ]:
a.size

6

In [ ]:
a.itemsize #total no of bytes

8

## Multi-dim array

In [ ]:
[[1,2,3],
 [4,5,6],
 [4,9,0]]

[[1, 2, 3], [4, 5, 6], [4, 9, 0]]

In [ ]:
a = np.array([[1,2,3],[4,5,6], [4,9,0]], dtype='int64')
print(a)

[[1 2 3]
 [4 5 6]
 [4 9 0]]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a[0]

array([1, 2, 3])

In [ ]:
a[0][2] #####

3

[[1 2 3]
 [4 5 6]
 [4 9 0]]

In [ ]:
a[0:9][0:1] #do not consider last one

array([[1, 2, 3]])

In [ ]:
a[0:10]

array([[1, 2, 3],
       [4, 5, 6],
       [4, 9, 0]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [4, 9, 0]])

In [ ]:
#a[1:3, 1:2][ 1:3, 2:2] Invalid statement

array([], shape=(1, 0), dtype=int64)

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a.size

9

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.itemsize

8

In [ ]:
a = np.array([[3,5,2,7], [9,0,1,6]])
a

array([[3, 5, 2, 7],
       [9, 0, 1, 6]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a_1 = np.reshape(a, (4, 2))

In [ ]:
a_1

array([[3, 5],
       [2, 7],
       [9, 0],
       [1, 6]])

In [ ]:
a_1.shape

(4, 2)

In [ ]:
# Convert into 1D
np.ravel(a)

array([3, 5, 2, 7, 9, 0, 1, 6])

# Basic Operations

In [ ]:
a = np.array([5, 9, 2, -3, 8, 1], dtype='int32')
b = np.array([7, 0, 2, 5, -9, 1], dtype='int32')

In [ ]:
a.min()

-3

In [ ]:
np.max(a)

9

In [ ]:
np.min(a)

-3

In [ ]:
np.argmax(a) #index of max value

4

In [ ]:
np.ceil(a)

array([[3., 5., 2., 7.],
       [9., 0., 1., 6.]])

In [ ]:
np.argmin(a)

3

In [ ]:
np.abs(a)

array([5, 9, 2, 3, 8, 1], dtype=int32)

In [ ]:
np.absolute(a)

array([5, 9, 2, 3, 8, 1], dtype=int32)

The functions np.absolute () and np.abs () are essentially the same. The np.abs () function is essentially a shorthand version np.absolute (). You can choose which ever one you like.

In [ ]:
np.sort(a)

array([-3,  1,  2,  5,  8,  9], dtype=int32)

In [ ]:
np.add(a, b)

array([12,  9,  4,  2, -1,  2], dtype=int32)

In [ ]:
np.subtract(a, b)

array([-2,  9,  0, -8, 17,  0], dtype=int32)

In [ ]:
np.append(a, [99, 88])

array([ 5,  9,  2, -3,  8,  1, 99, 88])

# Special Arrays

Numpy also provides many functions to create special arrays:

In [ ]:
np.arange(1, 8, 3) #first , last and 3 spacing

array([1, 4, 7])

In [ ]:
a = np.zeros((4,4))  # Create an array of all zeros
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
b = np.ones((3,5))   # Create an array of all ones
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
c = np.full((2,2), 'a') # Create a constant array
print(c)

[['a' 'a']
 ['a' 'a']]


In [ ]:
d = np.eye(3)        # Create a identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.random.random((2,3)) # Create an array filled with random values
print(e)

[[0.09482933 0.06800744 0.67598166]
 [0.02210637 0.97367333 0.51423361]]


## Boolean array indexing:
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
#print(a)

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
a = np.array([372,4,4,5])

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx

print(a[a > 99])

[372]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

## Math Operations

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors, multiplication and addition
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)

#You can also use the `@` operator which is equivalent to numpy's `dot` operator.

219
219
219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


## Computation Operations

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
print(x)

print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
# Transpose
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)


[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [ ]:
x = np.array([65, 34, 89])
np.sin(x)

array([0.82682868, 0.52908269, 0.86006941])

In [ ]:
np.cos(x)

array([-0.56245385, -0.84857027,  0.51017704])

# Random Numbers

In [ ]:
x=np.random.rand(4)                         # Produces random numbers between 0 and 1
print("Random numbers \n",x)
print(type(x))

Random numbers 
 [0.01733208 0.65302025 0.92115149 0.1950568 ]
<class 'numpy.ndarray'>


In [ ]:
a=np.random.randint(1,9,(4,4))              # Produces random int number
print(a)

[[5 1 2 5]
 [4 3 8 4]
 [8 2 8 5]
 [7 4 8 4]]


In [ ]:
print(np.random.random((5,5)))              # Simple and also for matrix

[[0.80657823 0.29226294 0.62427315 0.28267536 0.7949956 ]
 [0.50287896 0.01606125 0.71938884 0.64159114 0.90113068]
 [0.65323441 0.51170799 0.40443494 0.7482727  0.80428196]
 [0.76946345 0.25859336 0.55441872 0.88030789 0.00832115]
 [0.67084968 0.4966765  0.8254154  0.777935   0.39386513]]


In [ ]:
print((np.random.randn()))                  # Positive and negative

-1.8500047956138055


# Strings

In [ ]:
# Now string operations provided by numpy
s1="1$"
s2=" batch"
s=np.char.add(s2,s1)
print(s)

 batch1


In [ ]:
print(np.char.upper(s1))

1


In [ ]:
print(np.char.lower(s2))

 batch


In [ ]:
print(np.char.center(s2,8,fillchar="*"))

* batch*
